version: "3.9"

services:
  db:
    image: postgres
    container_name: postgre_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: web/
    container_name: flask_app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
