version: "3.9"

services:
  db:
    image: postgres
    container_name: postgre_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  web:
    build: ./services/web
    container_name: flask_app
    image: flask_image
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV
      - FLASK_APP
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT
    depends_on:
      - db
