version: "3.9"

services:
  db:
    image: postgres
    container_name: postgre_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

    env_file:
      - ./.env.dev
  web:
    build: ./services/web
    container_name: flask_app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
