version: "3.9"

services:
  db:
    image: postgres
    container_name: postgre_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_prod/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    # env_file:
    #   - .env.prod.db
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    image: flask_env
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    environment:
      - FLASK_ENV
      - FLASK_APP
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT
    # env_file:
    #   - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    container_name: gninx
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
