version: "3.9"

services:
  db:
    image: postgres
    container_name: postgre_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile.prod
    image: flask_env
    container_name: flask_app
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
