name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.HOST_DNS }}
      REMOTE_USER: ${{ secrets.USERNAME }}
      TARGET: ${{ secrets.TARGET_DIR }}
      FLASK_ENV: ${{ secrets.FLASK_ENV }}
      FLASK_APP: ${{ secrets.FLASK_APP }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2 Server
        uses: easingthemes/ssh-deploy@main

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        # with:
        #   host: ${{ secrets.HOST_DNS }}
        #   username: ${{ secrets.USERNAME }}
        #   key: ${{ secrets.SSH_KEY }}
        #   port: 22
        #   script_stop: true
        #   script: |
        #     docker-compose -f docker-compose.prod.yml up -d --build

      - name: Start containers
        run: docker-compose -f docker-compose.prod.yml up -d --build
